" konfiguracja vimrc

colo ayu
syntax on
se number
" se relativenumber
se autochdir
se autoread
se background=dark
se backspace=indent,eol,start
se clipboard+=unnamedplus
se cmdheight=2
se colorcolumn=+1
se complete+=kspell
se completeopt=menuone,noselect
se cursorline
se expandtab
se fillchars+="eob=' '"
se fillchars+=vert:\
se hidden
se ignorecase
se incsearch
se joinspaces
" se laststatus=2
se laststatus=3
se lazyredraw
se list
se listchars+=eol:¬
se listchars+=extends:»
se listchars+=precedes:«
se listchars+=tab:▸\ ,
se listchars+=trail:•
se listchars=nbsp:⦸
" se listchars=tab:▸\ ,eol:¬,extends:❯,precedes:❮     " ↲
se mouse=a
se nobackup
se nocompatible
se noshowmode
se noswapfile
se nowritebackup
se numberwidth=5
se path+=**
se path-=/usr/include
se pumheight=10
se scrolloff=4
se shiftround
se shiftwidth=4
se showbreak = "↪"
se sidescrolloff=8
se smarttab
se smartcase
se smartindent
se softtabstop=4
se splitbelow
se splitright
se t_Co=256
se tabstop=4
se termguicolors
se textwidth=100
se timeout
se timeoutlen=500
se ttimeout
se ttimeoutlen=500
se ttyfast
se undodir=~/.vim/undodir
se undofile
se undolevels=3333
se updatetime=300
se whichwrap+=<,>,h,l
se wildmenu
se wildmode=longest:full,full
se wrapscan
" se wrap
" se nolinebreak
" se term=xterm-256colors
" se linebreak
"
" let ayucolor="dark"
" let ayucolor="light"
" let ayucolor="mirage"

if has("nvim")
    se viminfo='100,n$HOME/.config/nvim/viminfo/viminfo
    se viewdir=$HOME/.config/nvim/view
    se directory=~/.config/nvim/swap//         " dir
else
    se viminfo+=n$HOME/.vim/viminfo/viminfo
    se viewdir=$HOME/.vim/view
    se directory=~/.vim/swap//                 " dir
    se cm=blowfish2
    " se key=tajne_hasło
endif
se viewoptions-=options

" augroup HelpMap
    " autocmd!
    autocmd! BufEnter,WinEnter,Filetype sh nnoremap K yiW:!man <c-r>"<cr>
    autocmd! BufEnter,WinEnter,Filetype vim nnoremap K yiW:help <c-r>"<cr>
" augroup END

nnoremap <leader>; :
nnoremap <leader>d :bd<cr>
nnorwmap <leader>q :q<cr>
nnoremap <leader>l :echom resolve(expand("%:p"))<cr>
nnoremap <leader>vs :vsplit<cr>
nnoremap <leader>sp :split<cr>
nnoremap <tab> :e #<cr>

